server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/sys_user
spring.datasource.username=postgres
spring.datasource.password=llq123

spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.database=0

mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.configuration.map-underscore-to-camel-case=true
